Remove reliance on GLFW for mock when disabled
The documentation states that the OpenGL backend can be disabled by
building with `cmake -DPOLYSCOPE_BACKEND_OPENGL3_GLFW=OFF ..`
However running make on the result leads to an error:

In file included from polyscope/src/../include/polyscope/render/opengl/shaders/common.h:8,
                 from
                 polyscope/src/render/mock_opengl/mock_gl_engine.cpp:13:
polyscope/src/../include/polyscope/render/opengl/gl_engine.h:12:10: fatal error: glad/glad.h: No such file or directory
   12 | #include "glad/glad.h"
      |          ^~~~~~~~~~~~~

This is due to the mocked backend depending on glad. This commit uses
compiler flags to disable that include.